### ISSUE TITLE
error on language change & restart

### ISSUE THREAD

**Issue by 0x6b656e** [anonymousbitcoin/anon-full-node-wallet#8]
Changed language and restarted and get this alert box message "A java exception has occurred" then it just closes and cannot get the wallet to open anymore

Ran via cmd line and this is the full error:

Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key LOCAL_MSG_TAB_MSTRNDE
        at java.util.ResourceBundle.getObject(Unknown Source)
        at java.util.ResourceBundle.getString(Unknown Source)
        at org.anonymous.wallets.fullnode.util.Util.local(Util.java:85)
        at org.anonymous.wallets.fullnode.ui.ANONWalletUI.<clinit>(ANONWalletUI.java:69)

**Comment by 0x6b656e** [comment]
Resolved in https://github.com/anonymousbitcoin/anon-full-node-wallet/pull/7/commits/1479a1171b635d3233c6e4c6499a7b1f4a5b2978

**Comment by 48thRonin** [comment]
Patches introduced
